#!/usr/bin/env bash
# Shared helpers for setup scripts
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

prompt() {
  local var_name="$1"
  local question="$2"
  local default="${3:-}"
  local value
  if [ -n "$default" ]; then
    read -r -p "$question [$default]: " value
    value="${value:-$default}"
  else
    read -r -p "$question: " value
  fi
  printf -v "$var_name" '%s' "$value"
}

prompt_secret() {
  local var_name="$1"
  local question="$2"
  local value
  read -r -s -p "$question: " value
  echo ""
  printf -v "$var_name" '%s' "$value"
}

prompt_yes_no() {
  local question="$1"
  local default="${2:-y}"
  local hint="Y/n"
  [ "$default" = "n" ] && hint="y/N"
  local answer
  read -r -p "$question [$hint]: " answer
  answer="${answer:-$default}"
  [[ "$answer" =~ ^[Yy] ]]
}

rand_hex() {
  openssl rand -hex "$1" 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex($1))"
}

wait_for_url() {
  local url="$1"
  local label="$2"
  local max="${3:-60}"
  local i=1
  while [ "$i" -le "$max" ]; do
    if curl -sf "$url" >/dev/null 2>&1; then
      echo "  ✓ $label"
      return 0
    fi
    sleep 2
    i=$((i + 1))
  done
  echo "  ✗ $label (timed out)"
  return 1
}

wait_for_postgres() {
  local max="${1:-30}"
  local i=1
  while [ "$i" -le "$max" ]; do
    if docker compose exec -T postgres pg_isready -U support_agent -d support_agent >/dev/null 2>&1; then
      echo "  ✓ PostgreSQL"
      return 0
    fi
    sleep 2
    i=$((i + 1))
  done
  echo "  ✗ PostgreSQL (timed out)"
  return 1
}

wait_for_ollama_models() {
  local max_minutes="${1:-20}"
  local max=$((max_minutes * 30))
  local i=0
  echo "  Waiting for Ollama models (up to ${max_minutes}m)..."
  while [ "$i" -lt "$max" ]; do
    if curl -sf http://localhost:11434/api/tags >/dev/null 2>&1; then
      local tags
      tags=$(curl -sf http://localhost:11434/api/tags | python3 -c "import sys,json; print(' '.join(m.get('name','') for m in json.load(sys.stdin).get('models',[])))" 2>/dev/null || echo "")
      if echo "$tags" | grep -q "llama3.2" && echo "$tags" | grep -q "nomic-embed-text"; then
        echo "  ✓ Ollama models ready (llama3.2, nomic-embed-text)"
        return 0
      fi
    fi
    sleep 2
    i=$((i + 1))
    if [ $((i % 15)) -eq 0 ]; then
      echo "    still pulling... ($(docker compose logs --tail=1 ollama-init 2>/dev/null | tail -1))"
    fi
  done
  echo "  ! Ollama models not confirmed yet — check: docker compose logs -f ollama-init"
  return 1
}

update_demo_config() {
  local token="$1"
  local url="${2:-http://localhost:5678/webhook/support-inquiry}"
  cat > "$PROJECT_DIR/demo/config.js" <<EOF
// Auto-generated by interactive-setup.sh
window.DEMO_CONFIG = {
  webhookUrl: "$url",
  webhookToken: "$token",
};
EOF
}

update_postgres_credential() {
  local password="$1"
  python3 <<PY
import json
path = "$PROJECT_DIR/n8n/credentials/postgres.json"
with open(path) as f:
    data = json.load(f)
data["data"]["password"] = "$password"
with open(path, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
PY
}

# --- UI helpers (guide session) — art + colors in scripts/art.sh ---
# shellcheck source=art.sh
source "$SCRIPT_DIR/art.sh"

open_url() {
  local url="$1"
  if command -v open >/dev/null 2>&1; then
    open "$url" 2>/dev/null || true
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$url" 2>/dev/null || true
  else
    say "Open in browser: $url"
  fi
}

load_env() {
  if [ -f "$PROJECT_DIR/.env" ]; then
    # shellcheck disable=SC1091
    set -a && source "$PROJECT_DIR/.env" && set +a
    return 0
  fi
  return 1
}

check_docker() {
  command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1
}

check_n8n() {
  curl -sf http://localhost:5678/healthz >/dev/null 2>&1
}

check_qdrant_seeded() {
  curl -sf http://localhost:6333/collections/support_kb >/dev/null 2>&1 || return 1
  local pts
  pts=$(curl -sf http://localhost:6333/collections/support_kb | python3 -c "import sys,json; print(json.load(sys.stdin).get('result',{}).get('points_count',0))" 2>/dev/null || echo "0")
  [ "${pts:-0}" -gt 0 ] 2>/dev/null
}

check_webhook() {
  load_env || return 1
  local code
  code=$(curl -s -o /dev/null -w "%{http_code}" \
    -X POST "http://localhost:5678/webhook/support-inquiry" \
    -H "Content-Type: application/json" \
    -H "X-Webhook-Token: ${WEBHOOK_AUTH_TOKEN:-}" \
    -d '{"customer_email":"test@example.com","message":"ping"}' \
    --max-time 10 2>/dev/null || echo "000")
  [ "$code" = "200" ] || [ "$code" = "500" ]
}

check_ollama_models() {
  curl -sf http://localhost:11434/api/tags >/dev/null 2>&1 || return 1
  local tags
  tags=$(curl -sf http://localhost:11434/api/tags | python3 -c "import sys,json; print(' '.join(m.get('name','') for m in json.load(sys.stdin).get('models',[])))" 2>/dev/null || echo "")
  echo "$tags" | grep -q "llama3.2" && echo "$tags" | grep -q "nomic-embed-text"
}

write_env_file() {
  local pg_pass="$1" token="$2" gmail="$3" tz="$4" ollama_host="$5"
  local enc jwt
  enc="$(rand_hex 16)"
  jwt="$(rand_hex 32)"
  cat > "$PROJECT_DIR/.env" <<EOF
# Generated by guide on $(date -u +%Y-%m-%dT%H:%MZ)
POSTGRES_USER=support_agent
POSTGRES_PASSWORD=${pg_pass}
POSTGRES_DB=support_agent

N8N_ENCRYPTION_KEY=${enc}
N8N_USER_MANAGEMENT_JWT_SECRET=${jwt}

OLLAMA_HOST=${ollama_host}
QDRANT_HOST=qdrant
QDRANT_PORT=6333

WEBHOOK_AUTH_TOKEN=${token}
INTENT_CONFIDENCE_THRESHOLD=0.55

GMAIL_FROM_ADDRESS=${gmail}
GENERIC_TIMEZONE=${tz}
EOF
}
